### ISSUE TITLE
Windows binaries aren't publishing to GitHub release page

### ISSUE THREAD

**Issue by superm1** [fwupd/fwupd#8477]
I noticed that from the most recent CI runs that the Windows MSI isn't getting published and looking further neither is the `news.txt` artifact from the Windows build.

This seems that it hasn't worked since we switched from Circle, so perhaps there is at least an impedance mismatch that was introduced somewhere.

**Comment by superm1** [comment]
I was really hoping it's an ordering problem that was causing issue, but unfortunately it seems that dist/news.txt still didn't update on 2.0.7 release.

**Comment by JohnAZoidberg** [comment]
I was just looking for the windows binary to use `fwupdtool.exe firmware-parse`. 
I'd find it useful to have the windows executables published.

**Comment by hughsie** [comment]
If it helps, I think they're one of the CI assets. I'm not entirely sure why it's not uploading as a release object.

**Comment by JohnAZoidberg** [comment]
> If it helps, I think they're one of the CI assets.

Yes, I'm using that and it works :D

> I'm not entirely sure why it's not uploading as a release object.

https://github.com/fwupd/fwupd/actions/runs/15758481460/job/44419440122
```
cat: dist/news.txt: No such file or directory
```

**Comment by JohnAZoidberg** [comment]
Awesome, thanks, looking forward to the next release

**Comment by JohnAZoidberg** [comment]
@hughsie it's still not there: https://github.com/fwupd/fwupd/releases/tag/2.0.14

**Comment by superm1** [comment]
According to the CI run:

```
Run svenstaro/upload-release-action@v2
Getting release by tag 2.0.14.
Error: No files matching the glob pattern found.
```

I re-ran the job and still it failed... hmm.

**Comment by superm1** [comment]
Our job has

```
      - name: Upload Binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file_glob: true
          file: dist/setup/*.msi
```

Which according to [documentation](https://github.com/svenstaro/upload-release-action) is what we should be using.

```
The tag to upload into. If you want the current event's tag or branch name, use ${{ github.ref }} (the refs/tags/ and refs/heads/ prefixes will be automatically stripped).
```
